# Generated by Django 3.2 on 2021-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bab', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='materi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField()),
                ('link', models.TextField()),
                ('deskripsi', models.TextField()),
                ('bab', models.ManyToManyField(to='blog_post.bab')),
            ],
        ),
        migrations.AddField(
            model_name='bab',
            name='kelas',
            field=models.ManyToManyField(to='blog_post.kelas'),
        ),
    ]
