# Generated by Django 3.2 on 2021-05-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
