# Generated by Django 3.2 on 2021-05-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_materi_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
