# Generated by Django 4.2.4 on 2023-08-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0002_remove_subscriptionplan_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_post.kelas'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='kelas',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog_post.kelas'),
        ),
    ]
