# Generated by Django 4.2.4 on 2023-08-28 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0003_alter_subscriptionplan_kelas_and_more'),
    ]

    operations = [
        
    ]
