# Generated by Django 4.2.4 on 2023-08-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_post', '0004_remove_subscriptionplan_name'),
    ]

    operations = [
       
        
        
    ]
